services:
  - name: insta-downloader-bot
    envVars:
      - key: API_ID
        value: "your_api_id"
      - key: API_HASH
        value: "your_api_hash"
      - key: BOT_TOKEN
        value: "your_bot_token"
    startCommand: "python3 bot/main.py"
